#!/usr/bin/env python3

import os
import sys
import json
from datetime import datetime

from flask import Flask, render_template, redirect, request

from app.form import ContactForm, csrf


### Config
app = Flask(__name__)
CONFIG_FILE = 'content.json'
HOST = 'http://127.0.0.1:5000'


SECRET_KEY = os.urandom(32)
app.config['SECRET_KEY'] = SECRET_KEY
csrf.init_app(app)

def load_config(fname=CONFIG_FILE):
    """read the content.json file and load it as a dictionary"""
    with open(fname, 'r') as f:
        return json.load(f)

CONFIG = load_config(CONFIG_FILE)

PAGES = {page['url']: page for page in  list(CONFIG['PAGES'].values())}  # {url: {page_data}}

### Routes

# Similar to wordpress, pages and posts are separate.  Every page has its own template
# in templates/page.html, but all posts use the same template + an iframe URL for the
# post content

@app.route('/')
def index():
    return redirect("/index.html")

@app.route('/favicon.ico')
def favicon():
    return redirect("/static/favicon.ico")

@app.route('/<path>')
def render_page(path):
    page = PAGES[f'/{path}']
    if page['url'] == '/contact_us.html':
        form = ContactForm()
        return render_template(page['template'], now=datetime.now(), **CONFIG, **page, form=form)
    return render_template(page['template'], now=datetime.now(), **CONFIG, **page)

@app.route('/contact_form', methods=['GET', 'POST'])
def contact_form():
    form = ContactForm()
    if form.validate_on_submit():
        index()
    else:
        page = PAGES['/contact_us.html']
        return render_template(page['template'], now=datetime.now(), **CONFIG, **page, form=form)

if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] == '--pages':
        # just print list of page urls
        #print('\n'.join(HOST + url for url in PAGES.keys()))
        """ elif len(sys.argv) > 1 and sys.argv[1] == '--posts':
        # just print list of post urls
        print('\n'.join(HOST + url for url in POSTS.keys())) """
    else:
        # run the flask http server
        app.run()
