#!/usr/bin/env python3

import os
import sys
import json
from datetime import datetime

from flask import Flask, render_template, redirect, request
from flask_mail import Mail, Message

from app.form import ContactForm, csrf

mail = Mail()
### Config
app = Flask(__name__)
CONFIG_FILE = 'content.json'
HOST = 'http://127.0.0.1:5000'


SECRET_KEY = os.urandom(32)
app.config['SECRET_KEY'] = SECRET_KEY
csrf.init_app(app)

#Configuring Flask-Mail
app.config['MAIL_SERVER']='smtp.gmail.com'
app.config['MAIL_PORT'] = 465
app.config['MAIL_USERNAME'] = 'testmonadical@gmail.com'
app.config['MAIL_PASSWORD'] = os.environ.get('EMAIL_PASS')
app.config['MAIL_USE_TLS'] = False
app.config['MAIL_USE_SSL'] = True
#app.config['TESTING'] = True
mail.init_app(app)


def load_config(fname=CONFIG_FILE):
    """read the content.json file and load it as a dictionary"""
    with open(fname, 'r') as f:
        return json.load(f)

CONFIG = load_config(CONFIG_FILE)

PAGES = {page['url']: page for page in  list(CONFIG['PAGES'].values())}  # {url: {page_data}}

### Routes

# Similar to wordpress, pages and posts are separate.  Every page has its own template
# in templates/page.html, but all posts use the same template + an iframe URL for the
# post content

@app.route('/')
def index():
    return redirect("/index.html")

@app.route('/favicon.ico')
def favicon():
    return redirect("/static/favicon.ico")

@app.route('/<path>')
def render_page(path):
    page = PAGES[f'/{path}']
    if page['url'] == '/contact_us.html':
        form = ContactForm()
        return render_template(page['template'], now=datetime.now(), **CONFIG, **page, form=form)
    return render_template(page['template'], now=datetime.now(), **CONFIG, **page)

@app.route('/contact_form', methods=['GET', 'POST'])
def contact_form():
    form = ContactForm()
    if form.validate_on_submit():
        send_message(request.form)
        return index()
        
    else:
        page = PAGES['/contact_us.html']
        return render_template(page['template'], now=datetime.now(), **CONFIG, **page, form=form)

def send_message(message):
    msg = Message(message.get('subject'), sender = message.get('email'),
            recipients = ['testmonadical@gmail.com'],
            body= f"{message.get('message')}. Send by {message.get('email')}"
    ) 
    mail.send(msg)
       

if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] == '--pages':
        # just print list of page urls
        print('\n'.join(HOST + url for url in PAGES.keys()))
    else:
        # run the flask http server
        app.run()
